# This file is part of pandas-learn
# https://github.com/RichLewis42/pandas-learn
#
# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT
# Copyright (c) 2015, Rich Lewis <rl403@cam.ac.uk>

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "nightly"
install:
  "pip install -r requirements.txt; pip install -r requirements_test.txt"

script:
  "nosetests"
