# This file is part of pandas-learn
# https://github.com/RichLewis42/pandas-learn
#
# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT
# Copyright (c) 2015, Rich Lewis <rl403@cam.ac.uk>
---
package:
    name: pdlearn
    version: 0.0.1

source:
    path: ..

build:
    number: 0

requirements:
    build:
      - python
      - pytest
      - coverage
      - nose
      - yanc

    run:
      - python
      - pandas
      - scikit-learn

test:
    requires:
      - pytest
      - coverage
      - nose
      - yanc

    imports:
      - pdlearn

about:
    home: https://github.com/richlewis42/pandas-learn
    license: MIT
    summary: Package allowing the use of pandas dataframes with scikit-learn classes.
